text:
  - platform: template
    name: "Song Single Click"
    id: !extend song_1
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "FrostyTh:d=4,o=5,b=160:2g,e.,8f,g,2c6,8h,8c6,d6,c6,h,a,2g.,8h,8c6,d6,c6,h,8a,8a,g,c6,e,8g,8a,g,f,e,f,1g;"
  - platform: template
    name: "Song Double Click"
    id: !extend song_2
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "WeWishYo:d=4,o=5,b=200:d,g,8g,8a,8g,8f#,e,e,e,a,8a,8b,8a,8g,f#,d,d,b,8b,8c6,8b,8a,g,e,d,e,a,f#,2g,d,g,8g,8a,8g,8f#,e,e,e,a,8a,8b,8a,8g,f#,d,d,b,8b,8c6,8b,8a,g,e,d,e,a,f#,1g,d,g,g,g,2f#,f#,g,f#,e,2d,a,b,8a,8a,8g,8g,d6,d,d,e,a,f#,2g;"
  - platform: template
    name: "Song Three Click"
    id: !extend song_3
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "LetItSno:d=8,o=5,b=125:c,c,c6,c6,4a#,4a,4g,4f,2c,c,c,4g.,f,4g.,f,4e,2c,4d,d6,d6,4c6,4a#,4a,2g.,e.6,16d6,4c6,c.6,16a#,4a,a#.,16a,2f.;"
  - platform: template
    name: "Song Four Click"
    id: song_4
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "AwayInA:d=4,o=6,b=25:16c#5,16f#5,16f#5,32g#5,32a#5,16f#5,16f#5,32a#5,32b5,16c#6,16c#6,16d#6,8b5,32g#5,32a#5,16b5,16b5,16c#6,16a#5,16a#5,32f#5,32a#5,16g#5,16d#5,16f#5,8f5,16c#5,16f#5,16f#5,32g#5,32a#5,16f#5,16f#5,16a#5,32b5,16c#6,16c#6,16d#6,8b5,32g#5,32a#5,16b5,16b5,16c#6,16a#5,16a#5,32f#5,32a#5,16g#5,16d#5,16f5,16f#.5;"
  - platform: template
    name: "Song Five Click"
    id: song_5
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value "SilentNi:d=4,o=5,b=112:g.,8a,g,2e.,g.,8a,g,2e.,2d6,d6,2b.,2c6,c6,2g.,2a,a,c6.,8b,a,g.,8a,g,2e.,2a,a,c6.,8b,a,g.,8a,g,2e.,2d6,d6,f6.,8d6,b,2c6.,2e6.,c6,g,e,g.,8f,d,2c.;"
  - platform: template
    name: "Song Long Click"
    id: song_6
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value"SoThisIs:d=4,o=6,b=160:c5,f5,g5,a5,f5,1c5,p,2p,c5,f5,g5,a5,8g5,8f5,1d5,p,2p,d5,g5,a5,a_5,a5,2g.5,1p,c5,a5,c,a5,8a5,8g5,1f5,p,2p,f5,d,d,d,c,1a_5,p,2p,f5,a_5,c,d,1c,1p,f5,c,d,d_,d,1c,p,2p,f5,d,f,d,8a_5,8g5,2f.5;"

binary_sensor:
  - platform: gpio
    id: !extend back_button
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
      allow_other_uses: true

    internal: true
    on_multi_click:
      #Single Click
      - timing:
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_1

    #  # Double Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_2

    #  # Triple Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_3
          
    #  # Four Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_4

          
    #  # Five Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_5
          
    #  # Long Click
      - timing:
          - ON for at least 1s
        then:
          - script.execute: play_song_6
          


