text:
  - platform: template
    name: "Song Single Click"
    id: !extend song_1
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "AwayInA:d=4,o=6,b=25:16c#5,16f#5,16f#5,32g#5,32a#5,16f#5,16f#5,32a#5,32b5,16c#6,16c#6,16d#6,8b5,32g#5,32a#5,16b5,16b5,16c#6,16a#5,16a#5,32f#5,32a#5,16g#5,16d#5,16f#5,8f5,16c#5,16f#5,16f#5,32g#5,32a#5,16f#5,16f#5,16a#5,32b5,16c#6,16c#6,16d#6,8b5,32g#5,32a#5,16b5,16b5,16c#6,16a#5,16a#5,32f#5,32a#5,16g#5,16d#5,16f5,16f#.5;"

  - platform: template
    name: "Song Double Click"
    id: !extend song_2
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "SilentNi:d=4,o=5,b=112:g.,8a,g,2e.,g.,8a,g,2e.,2d6,d6,2b.,2c6,c6,2g.,2a,a,c6.,8b,a,g.,8a,g,2e.,2a,a,c6.,8b,a,g.,8a,g,2e.,2d6,d6,f6.,8d6,b,2c6.,2e6.,c6,g,e,g.,8f,d,2c.;"

  - platform: template
    name: "Song Long Click"
    id: !extend song_3
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "SoThisIs:d=4,o=6,b=160:c5,f5,g5,a5,f5,1c5,p,2p,c5,f5,g5,a5,8g5,8f5,1d5,p,2p,d5,g5,a5,a_5,a5,2g.5,1p,c5,a5,c,a5,8a5,8g5,1f5,p,2p,f5,d,d,d,c,1a_5,p,2p,f5,a_5,c,d,1c,1p,f5,c,d,d_,d,1c,p,2p,f5,d,f,d,8a_5,8g5,2f.5;"
