text:
  - platform: template
    name: "Song 1 Single Click"
    id: !extend song_1
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "OhChrist:d=4,o=5,b=100:c,8f.,16f,f.,8g,8a.,16a,a.,8a,8g,8a,a#,e,g,f,8p,8c6,8c6,8a,d.6,8c6,8c6,8a#,a#.,8a#,8a#,8g,c.6,8a#,8a#,8a,a,8p,8c,8f.,8f,f,8g,8a.,16a,a.,8a,8g,8a,a#,e,g,f;"

  - platform: template
    name: "Song 2 Double Click"
    id: !extend song_2
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "snow:d=4,o=5,b=125:8c,8c,8c6,8c6,a#,a,g,f,2c,8c,8c,g.,8f,g.,8f,e,2c,d,8d6,8d6,c6,a#,a,2g.,8e.6,16d6,c6,8c.6,16a#,a,8a.,16g,2f.,c,8c6,8c6,a#,a,g,f,2c,8c.,16c,g.,8f,g.,8f,e,2c,d,8d6,8d6,c6,a#,a,2g.,8e.6,16d6,c6,8c.6,16a#,a,8a.,16g,2f.;"

  - platform: template
    name: "Song 3 Long Click"
    id: !extend song_3
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "carolbells:d=4,o=5,b=200:g,8f#,8g,e,g,8f#,8g,e,g,8f#,8g,e,g,8f#,8g,e,b,8a,8b,g,b,8a,8b,g,b,8a,8b,g,b,8a,8b,g,e6,8e6,8e6,8d6,8c6,b,8b,8b,8a,8g,a,8a,8a,8b,8a,e,8e,8e,e,8b4,8c#,8d#,8e,8f#,8g,8a,8b,a,g,8b4,8c#,8d#,8e,8f#,8g,8a,8b,a,g;"

