text:
  - platform: template
    name: "Song Single Click"
    id: !extend song_1
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "jingle:d=4,o=6,b=90:8a5,8a5,a5,8a5,8a5,a5,8a5,8c,8f5,8g5,a5,p,8a#5,8a#5,8a#.5,16a#5,8a#5,8a5,8a.5,16a5,8a5,8g5,8g5,8a5,g5,c,8a5,8a5,a5,8a5,8a5,a5,8a5,8c,8f5,8g5,a5,p,8a#5,8a#5,8a#.5,16a#5,8a#5,8a5,8a.5,16a5,8c,8c,8a5,8g5,f.5;"

  - platform: template
    name: "Song Double Click"
    id: !extend song_2
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "OhComeAl:d=4,o=5,b=160:g,2g,d,g,2a,2d,b,a,b,c6,2b,a,g,2g,f#,e,f#,g,a,b,2f#,e.,8d,2d.;"

  - platform: template
    name: "Song Three Click"
    id: !extend song_3
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "OhChrist:d=4,o=5,b=100:c,8f.,16f,f.,8g,8a.,16a,a.,8a,8g,8a,a#,e,g,f,8p,8c6,8c6,8a,d.6,8c6,8c6,8a#,a#.,8a#,8a#,8g,c.6,8a#,8a#,8a,a,8p,8c,8f.,8f,f,8g,8a.,16a,a.,8a,8g,8a,a#,e,g,f;"

  - platform: template
    name: "Song Four Click"
    id: song_4
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "CarolOfT:d=8,o=5,b=180:4a,g#,a,4f#,4a,g#,a,4f#,4f#6,f#6,f#6,e6,d6,4c#6,c#6,c#6,b,a,4b,b,b,c#6,b,4f#,f#,f#,4f#,c#,d#,e,f#,g#,a,b,c#6,4b,4a,c#,d#,e,f#,g#,a,b,c#6,4b,4a,4a,g#,a,4f#,4a,g#,a,4f#;"

  - platform: template
    name: "Song Five Click"
    id: song_5
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "SantaCla:d=4,o=5,b=160:16c,8e.,16f,g,2g,16g,8a.,16b,c6,2c6,8e.,16f,g,g,g,8a.,16g,f,2f,e,g,c,e,d,2f,b4,1c.,16c,8e.,16f,g,2g,16g,8a.,16b,c6,2c6,8e.,16f,g,g,g,8a.,16g,f,2f,e,g,c,e,d,2f,b4,1c.6;"

  - platform: template
    name: "Song Long Click"
    id: song_6
    icon: mdi:music-note
    entity_category: "config"
    restore_value: true
    mode: text
    optimistic: true
    initial_value: "RudolphT:d=16,o=6,b=100:32p,g#5,8a#5,g#5,8f5,8c#,8a#5,4g#.5,g#5,a#5,g#5,a#5,8g#5,8c#,2c,f#5,8g#5,f#5,8d#5,8c,8a#5,4g#.5,g#5,a#5,g#5,a#5,8g#5,8a#5,2f5,g#5,8a#5,a#5,8f5,8c#,8a#5,4g#.5,g#5,a#5,g#5,a#5,8g#5,8c#,2c,f#5,8g#5,f#5,8d#5,8c,8a#5,4g#.5,g#5,a#5,g#5,a#5,8g#5,8d#,2c#;"

binary_sensor:
  - platform: gpio
    id: !extend back_button
    pin:
      number: GPIO4
      inverted: true
      mode:
        input: true
        pullup: true
      allow_other_uses: true

    internal: true
    on_multi_click:
      #Single Click
      - timing:
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_1

    #  # Double Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_2

    #  # Triple Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_3
          
    #  # Four Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_4

          
    #  # Five Click
      - timing:
          - ON for at most 1s
          - OFF for at most 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
          - ON for at most 1s
          - OFF for at least 0.25s
        then:
          - script.execute: play_song_5
          
    #  # Long Click
      - timing:
          - ON for at least 1s
        then:
          - script.execute: play_song_6
          
script:
  - id: play_song_4
    then:
      - switch.turn_on: accessory_power
      - light.turn_on:
          brightness: 50%
          id: rgb_light
          effect: "RedGreen"
      - rtttl.play:
          rtttl: !lambda 'return id(song_3).state;'
      - delay: 30s
      - light.turn_off: rgb_light
      - switch.turn_off: accessory_power
      - if:
          condition:
            - switch.is_off: prevent_sleep
          then:
            - deep_sleep.enter:
                id: deep_sleep_1


  - id: play_song_5
    then:
      - switch.turn_on: accessory_power
      - light.turn_on:
          brightness: 50%
          id: rgb_light
          effect: "RedGreen"
      - rtttl.play:
          rtttl: !lambda 'return id(song_3).state;'
      - delay: 30s
      - light.turn_off: rgb_light
      - switch.turn_off: accessory_power
      - if:
          condition:
            - switch.is_off: prevent_sleep
          then:
            - deep_sleep.enter:
                id: deep_sleep_1


  - id: play_song_6
    then:
      - switch.turn_on: accessory_power
      - light.turn_on:
          brightness: 50%
          id: rgb_light
          effect: "RedGreen"
      - rtttl.play:
          rtttl: !lambda 'return id(song_3).state;'
      - delay: 30s
      - light.turn_off: rgb_light
      - switch.turn_off: accessory_power
      - if:
          condition:
            - switch.is_off: prevent_sleep
          then:
            - deep_sleep.enter:
                id: deep_sleep_1


