packages:
  ApolloAutomation.H-1: # name of package/project
    url: https://github.com/ApolloAutomation/H-1 # url of the repository
    ref: main # branch, tag or commit SHA
    files: [Integrations/ESPHome/H-1.yaml] # Path to config from base repo URL
    refresh: 1d # how often to sync updates from the remote url
  remote_package:
    url: https://github.com/lcgreenwald/H-1/
    ref: main
    files:
      - Integrations/ESPHome/MyTunes.yaml
    refresh: 1d
